name: Test reporter on test repo

on:
  workflow_dispatch:
    inputs:
      node-version:
        required: true
        type: string
        description: Node version to use
        default: '16.x'

jobs:
  test_run:
    name: Test reporter on test repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install internal repo dependencies
        run: |
          cd test_repo/test-app
          npm ci --include=dev
      - name: Install dependencies
        run: npm ci --omit=dev
      - name: Build Typescript
        run: npm run build
      - name: Run integration test with default reporter
        run: npm run integration-base
        continue-on-error: true
        env:
          FORCE_COLOR: 3
      - name: Run integration test with new reporter
        run: npm run integration-new
        continue-on-error: true
        env:
          FORCE_COLOR: 3