name: Release

on:
  push:
    tags:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: Test node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install production and development dependencies
        run: npm ci --include=dev
      - name: Run Tests
        run: npm run test
  build_and_release:
    runs-on: ubuntu-latest
    needs: test
    name: Build and release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Install production dependencies
        run: npm ci --ompit=dev
      - name: Publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}