name: Tests

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x, '20.x']
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: Test node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install production and development dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
        env:
          FORCE_COLOR: 3
  lint_and_build:
    runs-on: ubuntu-latest
    name: Lint and build code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Check prettier format
        run: npm run format-check
      - name: Check eslint
        run: npm run lint
      - name: Build Typescript
        run: npm run build
  codeql:
    runs-on: ubuntu-latest
    name: CodeQL Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Remove internal test repo
        run: rm -rf test_repo
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2