name: Tests

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: Test node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install production and development dependencies
        run: npm ci --include=dev
      - name: Run Tests
        run: npm run test
        env:
          FORCE_COLOR: 3
  codeql:
    needs: test
    runs-on: ubuntu-latest
    name: CodeQL Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Remove internal test repo
        run: rm -rf test_repo
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2